config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'home#index'
  root to: "home#index"

  scope :auth do
    post 'sign_in', to: 'auth#user_session'
    get 'sign_in', to: 'auth#new_user_session'
    get 'sign_out', to: 'auth#destroy_user_session'
  end

  resources :tasks, only: [:index, :show]
  resources :categories, only: [:index]
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  def get_current_user_id
    helpers.get_attribute_value_from(session[:auth_user], 'id')
  end

  private
  def require_login
    unless session.has_key?(:auth_user)
      redirect_to(controller: 'auth', action: 'new_user_session')
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  skip_before_action :require_login, only: [:new_user_session, :user_session]

  def new_user_session
    render :login
  end

  def user_session
    begin
      session[:auth_headers] = { content_type: "application/json" }
      response = helpers.post_resource('/auth/sign_in', params)
      session[:auth_user] = JSON.parse(response.body, :symbolize_names => true)[:data]
      session[:auth_headers] = response.headers.without(:transfer_encoding)
      flash[:success] = "Successo."
      redirect_to(home_path)
    rescue Exception => e
      reset_session
      helpers.flash_errors(e.response)
      render :login
    end
  end

  def destroy_user_session
    begin
      response = helpers.get_resource('/auth/sign_out', params)
      reset_session
      redirect_to(action: :new_user_session)
    rescue Exception => e
      redirect_to(action: :new_user_session)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = helpers.get_resources(:categories)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_categories, only: [:new, :edit, :create, :update]
  before_action :set_project, only: [:show, :edit]

  def index
# abort params.inspect
    @projects = helpers.get_resources(:projects, params[:term])
  end

  def new
  end

  def create
    begin
      helpers.post_resource(:projects, params.merge(user_id: get_current_user_id))
      redirect_to(projects_path, flash: helpers.flash_success(:created))
    rescue Exception => e
      helpers.flash_errors(e.response)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    begin
      helpers.put_resource(:projects, params.merge(user_id: get_current_user_id))
      redirect_to(projects_path, flash: helpers.flash_success(:updated))
    rescue Exception => e
      helpers.flash_errors(e.response)
      render :edit
    end
  end

  def destroy
    begin
      helpers.delete_resource(:projects, params)
      redirect_to(projects_path, flash: helpers.flash_success(:deleted))
    rescue Exception => e
      helpers.flash_errors(e.response)
      redirect_to(projects_path, flash: helpers.flash_success(:updated))
    end
  end

  private
  def set_project
    @project = helpers.get_resource(:projects, params)
  end

  def set_categories
    result = helpers.get_resources(:categories)

    @categories = helpers.get_collection(result).collect{ |category|
      [category[:attributes][:name], category[:id]]
    }
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = helpers.get_resources(:tasks)
  end

  def show
    @task = helpers.get_resource(:tasks, params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def post_resource(resource, params)
    uri = "#{ENV['API_BASE_URL']}/#{resource}"
    response = RestClient::Resource.new(uri)
    response.post(params.to_json, session[:auth_headers])
  end

  def put_resource(resource, params)
    uri = "#{ENV['API_BASE_URL']}/#{resource}/#{params[:id]}"
    response = RestClient::Resource.new(uri)
    response.put(params.to_json, session[:auth_headers])
  end

  def delete_resource(resource, params)
    uri = "#{ENV['API_BASE_URL']}/#{resource}/#{params[:id]}"
    response = RestClient::Resource.new(uri)
    response.delete(session[:auth_headers])
  end

  def get_resources(resource, term = '')
    uri = "#{ENV['API_BASE_URL']}/#{resource}"

    headers = session[:auth_headers]
    headers['params'] = {term: term}
    response = RestClient.get(uri, headers)
    JSON.parse(response.body, :symbolize_names => true)
  end

  def get_resource(resource, params)
    uri = "#{ENV['API_BASE_URL']}/#{resource}/#{params[:id]}"
    response = RestClient::Resource.new(uri).get(session[:auth_headers])
    JSON.parse(response.body, :symbolize_names => true)
  end

  def get_collection(hash)
    hash[:data] || []
  end

  def get_attribute_value_from(hash, key)
    hash = hash.key?(:data) ? hash[:data] : hash
    return hash[key] if hash.key?(key)
    hash = hash.key?(:attributes) ? hash[:attributes] : hash
    value = hash.key?(key) ? hash[key] : '...'
    value.instance_of?(String) ? value.capitalize : value
  end

  def get_relationship_attribute_value_from(hash, relation, key)
    hash = hash.key?(:data) ? hash[:data] : hash
    hash = hash.key?(:relationships) ? hash[:relationships] : hash
    hash = hash.key?(relation) ? hash[relation] : hash
    hash = hash.key?(:data) ? hash[:data] : hash
    value = hash.key?(key) ? hash[key] : '...'
    value.instance_of?(String) ? value.capitalize : value
  end

  def get_relationship_from(hash, relation)
    hash = hash.key?(:data) ? hash[:data] : hash
    hash = hash.key?(:relationships) ? hash[:relationships] : hash
    hash = hash.key?(relation) ? hash[relation] : hash
    hash.key?(:data) ? hash[:data] : []
  end

  def flash_success(action)
    { success: t(action, scope: [:message]) }
  end

  def flash_errors(errors)
    full_msg = "<ul>"
    JSON.parse(errors, :symbolize_names => true).each do |msg|
      full_msg << "<li>#{msg}</li>"
    end
    full_msg << "</ul>"
    flash.now[:error] = full_msg
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/categories/index.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">
      <strong> <%= t(:other, scope: [:models, :category]) %> </strong>
    </h3>
  </div>
  <div class="box-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><%= t(:name, scope: [:models, :category, :attributes]) %></th>
        </tr>
      </thead>
      <tbody>
        <% get_collection(@categories).each do |category| %>
          <tr>
            <td>
              <%= get_attribute_value_from(category, :name) %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<h2>Bem Vindo(a) <%= get_attribute_value_from(session[:auth_user], 'name') %></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Fractal</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- Google Font -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <!-- Main Navbar -->
      <%= render 'shared/navbar'%>
      <!-- Main Sidebar -->
      <%= render 'shared/sidebar'%>
      <!-- Content Wrapper -->
      <div class="content-wrapper">
        <!-- Main content -->
        <section class="content container-fluid">
          <%= yield %>
        </section>
      </div> <!-- /.content -->
    </div> <!-- /.content-wrapper -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/toastr' %>
  </body>
</html>

app/views/layouts/auth.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Desafio Fractal</title>
  <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <!-- Google Font -->
      <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
      <!-- Google Font -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition login-page">
  <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'shared/toastr' %>
</body>

</html>

app/views/projects/_form.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%= title %>
    </h3>
  </div>
  <%= form_tag({controller: "projects", action: action}, method: method, class: "form-horizontal") do %>
    <div class="box-body">
      <div class="form-group">
        <label class="col-sm-2 control-label">
          <%= t(:one, scope: [:models, :category]) %>
        </label>
        <div class="col-sm-10">
          <%= select_tag :category_id,
             options_for_select(
               @categories, @project.present? ? get_relationship_attribute_value_from(@project, :category, :id) : params[:category_id],
             ),
             include_blank: 'Selecionar...',
             class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">
          <%= t(:name, scope: [:models, :project, :attributes]) %>
        </label>
        <div class="col-sm-10">
          <%= text_field_tag :name,
            @project.present? ? get_attribute_value_from(@project, :name) : params[:name],
            class: "form-control",
            placeholder: "Nome" %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">
          <%= t(:description, scope: [:models, :project, :attributes]) %>
        </label>
        <div class="col-sm-10">
          <%= text_area_tag :description,
            @project.present? ? get_attribute_value_from(@project, :description) : params[:description],
            class: "form-control",
            rows: 5,
            placeholder: "Descrição" %>
        </div>
      </div>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">
      <%= link_to 'Voltar', projects_path, class: "btn btn-default" %>
        <button type="submit" class="btn btn-info pull-right">
          <%= action_btn %>
        </button>
    </div>
    <!-- /.box-footer -->
    <% end %>
</div>

app/views/projects/edit.html.erb
<%= render 'form',
  action: 'update',
  method: 'put',
  title: "#{t(:edit, scope: [:actions])} #{t(:one, scope: [:models, :project])}",
  action_btn: t(:update, scope: [:actions]) %>

app/views/projects/index.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">
      <strong> <%= t(:other, scope: [:models, :project]) %> </strong>
    </h3>
    <div class="pull-right">
      <%= link_to t(:create, scope: [:actions]), new_project_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <div class="box-body">
    <%= form_tag({controller: :projects, action: :index}, method: :get) do %>
      <%= text_field_tag :term, nil, class: 'form-control', placeholder: 'Digite um termo' %>
    <% end %>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><%= t(:name, scope: [:models, :project, :attributes]) %></th>
          <th><%= t(:one, scope: [:models, :category ]) %></th>
          <th>
            <%= t(:other, scope: [:models, :task ]) %>
          </th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% get_collection(@projects).each do |project| %>
          <tr>
            <td>
              <%= get_attribute_value_from(project, :name) %>
            </td>
            <td>
              <%= get_relationship_attribute_value_from(project, :category, :name) %>
            </td>
            <td>
              <%= get_relationship_from(project, :tasks).count %>
            </td>
            <td>
              <%= link_to t(:show, scope: [:actions]), project_path(project[:id]) %>
            </td>
            <td>
              <%= link_to t(:edit, scope: [:actions]), edit_project_path(project[:id]) %>
            </td>
            <td>
              <%= link_to t(:delete, scope: [:actions]), project_path(project[:id]), :method => :delete %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form',
  action: 'create',
  method: 'post',
  title: "#{t(:create, scope: [:actions])} #{t(:one, scope: [:models, :project])}",
  action_btn: t(:create, scope: [:actions]) %>

app/views/projects/show.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%= get_attribute_value_from(@project, :name) %>
    </h3>
  </div>
  <div class="box-body">
    <p>
      <strong><%= t(:one, scope: [:models, :category]) %>:</strong>
      <%= get_relationship_attribute_value_from(@project, :category, :name) %>
    </p>

    <p>
      <strong>
        <%= t(:description, scope: [:models, :project, :attributes]) %>:
      </strong>
      <%= get_attribute_value_from(@project, :description) %>
    </p>

  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <%= link_to 'Voltar', projects_path, class: "btn btn-default" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">
      <b>A</b>DM</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b></span>
  </a>
  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li>
          <a href="/auth/sign_out">
            <i class="fa fa-logout"></i> Sair
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_sidebar.html.erb
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu tree" data-widget="tree">
      <li class="header">MENU</li>
      <!-- Optionally, you can add icons to the links -->
      <li class="">
        <a href="/">
          <i class="fa fa-home"></i>
          <span><%= t(:one, scope: [:models, :home]) %></span>
        </a>
      </li>
      <li class="">
        <a href="/projects">
          <i class="fa fa-sitemap"></i>
          <span>
            <%= t(:other, scope: [:models, :project]) %>
          </span>
        </a>
      </li>
      <li class="">
        <a href="/tasks">
          <i class="fa fa-tasks"></i>
          <span><%= t(:other, scope: [:models, :task]) %></span>
        </a>
      </li>
      <li class="">
        <a href="/categories">
          <i class="fa fa-tags"></i>
          <span>
            <%= t(:other, scope: [:models, :category]) %>
          </span>
        </a>
      </li>
    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/shared/_toastr.html.erb
<% unless flash.empty? %>
  <% flash.each do |type, msg| %>
  <script type="text/javascript">
    toastr['<%= type %>']('<%= msg.html_safe %>');
  </script>
  <% end %>
<% end %>

app/views/tasks/index.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">
      <strong> <%= t(:other, scope: [:models, :task]) %> </strong>
    </h3>
  </div>
  <div class="box-body">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th><%= t(:name, scope: [:models, :task, :attributes]) %></th>
          <th><%= t(:one, scope: [:models, :project ]) %></th>
          <th><%= t(:done, scope: [:models, :task, :attributes]) %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% get_collection(@tasks).each do |task| %>
          <tr>
            <td>
              <%= get_attribute_value_from(task, :name) %>
            </td>
            <td>
              <%= get_relationship_attribute_value_from(task, :project, :name) %>
            </td>
            <td>
              <%= get_attribute_value_from(task, :done) %>
            </td>
            <td>
              <%= link_to t(:show, scope: [:actions]), controller: task[:type], action: 'show', id: task[:id] %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="box box-info">
  <div class="box-header with-border">
    <h3 class="box-title">
      <%= get_attribute_value_from(@task, :name) %>
    </h3>
  </div>
  <div class="box-body">
    <p>
      <strong><%= t(:one, scope: [:models, :project]) %>:</strong>
      <%= get_relationship_attribute_value_from(@task, :project, :name) %>
    </p>

    <p>
      <strong>
        <%= t(:description, scope: [:models, :task, :attributes]) %>:
      </strong>
      <%= get_attribute_value_from(@task, :description) %>
    </p>
  </div>
  <!-- /.box-body -->
  <div class="box-footer">
    <%= link_to 'Voltar', tasks_path, class: "btn btn-default" %>
  </div>
</div>